import { NextResponse } from 'next/server';

const INVENTORY_PRODUCTS = [
  {
    _id: 'prd_001',
    sku: 'WIQ-BEA-001',
    name: 'Vitamin C Brightening Serum (30ml)',
    category: 'Beauty & Personal Care',
    brand: 'GlowAura D2C',
    quantity: 450,
    reservedQuantity: 42,
    availableQuantity: 408,
    reorderLevel: 50,
    fulfillmentCenter: 'WareIQ Delhi NCR Fulfillment Hub',
    status: 'In Stock',
  },
  {
    _id: 'prd_002',
    sku: 'WIQ-BEA-002',
    name: 'Hydrating Peptide Night Cream (50g)',
    category: 'Beauty & Personal Care',
    brand: 'GlowAura D2C',
    quantity: 18,
    reservedQuantity: 12,
    availableQuantity: 6,
    reorderLevel: 25,
    fulfillmentCenter: 'WareIQ Bengaluru Tech Logistics Center',
    status: 'Low Stock',
  },
  {
    _id: 'prd_003',
    sku: 'WIQ-APP-101',
    name: 'Organic Cotton Oversized Tee (Navy - M)',
    category: 'Fashion & Apparel',
    brand: 'UrbanThread',
    quantity: 320,
    reservedQuantity: 28,
    availableQuantity: 292,
    reorderLevel: 40,
    fulfillmentCenter: 'WareIQ Mumbai Mega Gateway',
    status: 'In Stock',
  },
  {
    _id: 'prd_004',
    sku: 'WIQ-APP-102',
    name: 'Cargo Utility Joggers (Olive - L)',
    category: 'Fashion & Apparel',
    brand: 'UrbanThread',
    quantity: 0,
    reservedQuantity: 0,
    availableQuantity: 0,
    reorderLevel: 30,
    fulfillmentCenter: 'WareIQ Pune Fulfillment Center',
    status: 'Out of Stock',
  },
  {
    _id: 'prd_005',
    sku: 'WIQ-ELE-201',
    name: 'True Wireless Active ANC Earbuds',
    category: 'Consumer Electronics',
    brand: 'VoltSonic',
    quantity: 210,
    reservedQuantity: 15,
    availableQuantity: 195,
    reorderLevel: 30,
    fulfillmentCenter: 'WareIQ Bengaluru Tech Logistics Center',
    status: 'In Stock',
  },
  {
    _id: 'prd_006',
    sku: 'WIQ-NUT-301',
    name: 'Plant-Based High Protein Isolate (1kg)',
    category: 'Health & Wellness',
    brand: 'NutriPeak',
    quantity: 180,
    reservedQuantity: 24,
    availableQuantity: 156,
    reorderLevel: 35,
    fulfillmentCenter: 'WareIQ Hyderabad Regional FC',
    status: 'In Stock',
  },
  {
    _id: 'prd_007',
    sku: 'WIQ-HOM-401',
    name: 'Ergonomic Memory Foam Lumbar Cushion',
    category: 'Home & Living',
    brand: 'ComfortCraft',
    quantity: 95,
    reservedQuantity: 10,
    availableQuantity: 85,
    reorderLevel: 20,
    fulfillmentCenter: 'WareIQ Delhi NCR Fulfillment Hub',
    status: 'In Stock',
  },
];

export async function GET() {
  return NextResponse.json({
    success: true,
    data: INVENTORY_PRODUCTS,
    meta: {
      total: INVENTORY_PRODUCTS.length,
      page: 1,
      limit: 20,
    },
  });
}
