export const SEED_USERS = [
  {
    name: 'WareIQ Master Admin',
    email: 'admin@wareiq-demo.com',
    password: 'Password@123',
    role: 'admin',
    companyName: 'WareIQ India Logistics HQ',
    phone: '+91 98765 43210',
    isActive: true,
  },
  {
    name: 'Operations Dispatch Manager',
    email: 'ops@wareiq-demo.com',
    password: 'Password@123',
    role: 'operations',
    companyName: 'WareIQ Bhiwandi Central FC',
    phone: '+91 98765 43211',
    isActive: true,
  },
  {
    name: 'Manoj Arja (Demo Merchant)',
    email: 'demo@brandmerchant.com',
    password: 'Password@123',
    role: 'customer',
    companyName: 'Acme D2C Brands India',
    phone: '+91 98765 43212',
    isActive: true,
  },
];

export const SEED_FULFILLMENT_CENTERS = [
  {
    name: 'WareIQ Delhi NCR Fulfillment Hub',
    city: 'Gurugram',
    state: 'Haryana',
    zone: 'North',
    address: 'Plot 42, Sector 37 Logistics Park, Pace City II',
    pincode: '122001',
    services: ['Same-Day Dispatch', 'D2C Fulfillment', 'Marketplace Staging', 'Cold Storage'],
    operatingStatus: 'Active',
    capacityPercentage: 78,
  },
  {
    name: 'WareIQ Mumbai Mega Gateway',
    city: 'Bhiwandi',
    state: 'Maharashtra',
    zone: 'West',
    address: 'Bldg B3, Indian Logistics City, Mankoli',
    pincode: '421302',
    services: ['Same-Day Dispatch', 'B2B Palletizing', 'Dark Store Staging', 'SOR Hub'],
    operatingStatus: 'Active',
    capacityPercentage: 84,
  },
  {
    name: 'WareIQ Bengaluru Tech Logistics Center',
    city: 'Bengaluru',
    state: 'Karnataka',
    zone: 'South',
    address: 'Indospace Industrial Park, Hosakote High-Tech Zone',
    pincode: '562114',
    services: ['Same-Day Delivery', 'Quick Commerce Dark Store Staging', 'Serial Tracking'],
    operatingStatus: 'Active',
    capacityPercentage: 69,
  },
  {
    name: 'WareIQ Hyderabad Regional FC',
    city: 'Hyderabad',
    state: 'Telangana',
    zone: 'South',
    address: 'Survey 108, Medchal Industrial Corridor',
    pincode: '501401',
    services: ['D2C Fulfillment', 'Pharma & Wellness Storage', 'Smart Routing'],
    operatingStatus: 'Active',
    capacityPercentage: 62,
  },
  {
    name: 'WareIQ Kolkata Gateway Hub',
    city: 'Kolkata',
    state: 'West Bengal',
    zone: 'East',
    address: 'NH-2 Industrial Cluster, Dankuni',
    pincode: '712311',
    services: ['East Hub Transshipment', 'Marketplace Inbounding', 'Multi-carrier Sorting'],
    operatingStatus: 'Active',
    capacityPercentage: 58,
  },
  {
    name: 'WareIQ Pune Fulfillment Center',
    city: 'Pune',
    state: 'Maharashtra',
    zone: 'West',
    address: 'MIDC Phase II, Chakan Logistics Park',
    pincode: '410501',
    services: ['Automated Sorting', 'Apparel QC Station', 'D2C Next-Day'],
    operatingStatus: 'Active',
    capacityPercentage: 72,
  },
];

export const SEED_PRODUCTS = [
  {
    sku: 'WIQ-BEA-001',
    name: 'Vitamin C Brightening Serum (30ml)',
    category: 'Beauty & Personal Care',
    brand: 'GlowAura D2C',
    quantity: 450,
    reservedQuantity: 42,
    reorderLevel: 50,
    fulfillmentCenter: 'WareIQ Delhi NCR Fulfillment Hub',
  },
  {
    sku: 'WIQ-BEA-002',
    name: 'Hydrating Peptide Night Cream (50g)',
    category: 'Beauty & Personal Care',
    brand: 'GlowAura D2C',
    quantity: 18,
    reservedQuantity: 12,
    reorderLevel: 25,
    fulfillmentCenter: 'WareIQ Bengaluru Tech Logistics Center',
  },
  {
    sku: 'WIQ-APP-101',
    name: 'Organic Cotton Oversized Tee (Navy - M)',
    category: 'Fashion & Apparel',
    brand: 'UrbanThread',
    quantity: 320,
    reservedQuantity: 28,
    reorderLevel: 40,
    fulfillmentCenter: 'WareIQ Mumbai Mega Gateway',
  },
  {
    sku: 'WIQ-APP-102',
    name: 'Cargo Utility Joggers (Olive - L)',
    category: 'Fashion & Apparel',
    brand: 'UrbanThread',
    quantity: 0,
    reservedQuantity: 0,
    reorderLevel: 30,
    fulfillmentCenter: 'WareIQ Pune Fulfillment Center',
  },
  {
    sku: 'WIQ-ELE-201',
    name: 'True Wireless Active ANC Earbuds',
    category: 'Consumer Electronics',
    brand: 'VoltSonic',
    quantity: 210,
    reservedQuantity: 15,
    reorderLevel: 30,
    fulfillmentCenter: 'WareIQ Bengaluru Tech Logistics Center',
  },
  {
    sku: 'WIQ-NUT-301',
    name: 'Plant-Based High Protein Isolate (1kg)',
    category: 'Health & Wellness',
    brand: 'NutriPeak',
    quantity: 180,
    reservedQuantity: 24,
    reorderLevel: 35,
    fulfillmentCenter: 'WareIQ Hyderabad Regional FC',
  },
  {
    sku: 'WIQ-HOM-401',
    name: 'Ergonomic Memory Foam Lumbar Cushion',
    category: 'Home & Living',
    brand: 'ComfortCraft',
    quantity: 95,
    reservedQuantity: 10,
    reorderLevel: 20,
    fulfillmentCenter: 'WareIQ Delhi NCR Fulfillment Hub',
  },
];

export const SEED_LEADS = [
  {
    firstName: 'Vikram',
    lastName: 'Singhania',
    email: 'vikram@lumoscosmetics.in',
    phone: '9820198201',
    companyName: 'Lumos Cosmetics India',
    operatingLocation: 'Mumbai & Delhi NCR',
    enquiryType: 'D2C Fulfillment',
    challenges: 'High RTO rate (34%) and delayed 5-day delivery times across tier 2 cities.',
    monthlyOrders: '10,000 - 25,000 orders/mo',
    warehouseCount: 'Currently self-fulfilled from 1 warehouse',
    businessLocation: 'Mumbai',
    requirements: 'Pan-India 2-day delivery with automated NDR WhatsApp bot.',
    source: 'Google Search',
    status: 'Qualified',
    notes: 'High potential enterprise lead. Needs same-day dispatch cutoff till 4 PM.',
  },
  {
    firstName: 'Priya',
    lastName: 'Nambiar',
    email: 'priya@pureearthfoods.com',
    phone: '9945099450',
    companyName: 'Pure Earth Organic Superfoods',
    operatingLocation: 'Bengaluru',
    enquiryType: 'Quick Commerce Fulfillment',
    challenges: 'Stockouts on Blinkit and Zepto dark stores causing 40% loss of daily sales.',
    monthlyOrders: '25,000+ orders/mo',
    warehouseCount: 'Looking for 4 regional staging hubs',
    businessLocation: 'Bengaluru',
    requirements: 'Dark store replenishment micro-SLAs within 2 hours.',
    source: 'LinkedIn',
    status: 'Proposal',
    notes: 'Draft proposal shared for Bangalore, Mumbai, and Gurgaon hubs.',
  },
  {
    firstName: 'Rohan',
    lastName: 'Kapoor',
    email: 'rohan@gearupfit.co',
    phone: '9811298112',
    companyName: 'GearUp Fitness Tech',
    operatingLocation: 'Delhi NCR',
    enquiryType: 'Marketplace Fulfillment',
    challenges: 'Strict Amazon Seller Flex and Flipkart SLA compliance penalties.',
    monthlyOrders: '5,000 - 10,000 orders/mo',
    warehouseCount: '1 facility',
    businessLocation: 'Gurugram',
    requirements: 'Amazon Seller Flex prep and appointment scheduling.',
    source: 'Website Direct Demo Request',
    status: 'New',
    notes: 'Requested immediate callback for Q4 festive sale preparation.',
  },
];

export const SEED_ORDERS = [
  {
    orderId: 'WIQ-ORD-1001',
    customerName: 'Ananya Sharma',
    channel: 'D2C',
    orderDate: new Date(Date.now() - 3600000 * 36),
    fulfillmentCenter: 'WareIQ Delhi NCR Fulfillment Hub',
    items: [
      { sku: 'WIQ-BEA-001', name: 'Vitamin C Brightening Serum (30ml)', quantity: 2, unitPrice: 799 },
    ],
    totalItems: 2,
    totalAmount: 1598,
    paymentStatus: 'Paid',
    fulfillmentStatus: 'Fulfilled',
    shippingStatus: 'In Transit',
    courier: 'Delhivery',
    awbNumber: 'WIQ-AWB-2026-1001',
    deliveryCity: 'Jaipur',
    pincode: '302001',
    expectedDeliveryDate: new Date(Date.now() + 3600000 * 24),
  },
  {
    orderId: 'WIQ-ORD-1002',
    customerName: 'Rajesh Nair',
    channel: 'Marketplace',
    orderDate: new Date(Date.now() - 3600000 * 48),
    fulfillmentCenter: 'WareIQ Bengaluru Tech Logistics Center',
    items: [
      { sku: 'WIQ-ELE-201', name: 'True Wireless Active ANC Earbuds', quantity: 1, unitPrice: 2499 },
    ],
    totalItems: 1,
    totalAmount: 2499,
    paymentStatus: 'Paid',
    fulfillmentStatus: 'Fulfilled',
    shippingStatus: 'Delivered',
    courier: 'BlueDart',
    awbNumber: 'WIQ-AWB-2026-1002',
    deliveryCity: 'Chennai',
    pincode: '600018',
    expectedDeliveryDate: new Date(Date.now() - 3600000 * 12),
    deliveredAt: new Date(Date.now() - 3600000 * 10),
  },
  {
    orderId: 'WIQ-ORD-1003',
    customerName: 'Devika Patel',
    channel: 'D2C',
    orderDate: new Date(Date.now() - 3600000 * 18),
    fulfillmentCenter: 'WareIQ Mumbai Mega Gateway',
    items: [
      { sku: 'WIQ-APP-101', name: 'Organic Cotton Oversized Tee (Navy - M)', quantity: 1, unitPrice: 1299 },
    ],
    totalItems: 1,
    totalAmount: 1299,
    paymentStatus: 'COD',
    fulfillmentStatus: 'Fulfilled',
    shippingStatus: 'NDR',
    courier: 'Xpressbees',
    awbNumber: 'WIQ-AWB-2026-1003',
    deliveryCity: 'Ahmedabad',
    pincode: '380015',
    expectedDeliveryDate: new Date(Date.now() + 3600000 * 12),
  },
  {
    orderId: 'WIQ-ORD-1004',
    customerName: 'Suresh Menon',
    channel: 'Quick Commerce',
    orderDate: new Date(Date.now() - 3600000 * 60),
    fulfillmentCenter: 'WareIQ Bengaluru Tech Logistics Center',
    items: [
      { sku: 'WIQ-NUT-301', name: 'Plant-Based High Protein Isolate (1kg)', quantity: 2, unitPrice: 1899 },
    ],
    totalItems: 2,
    totalAmount: 3798,
    paymentStatus: 'Paid',
    fulfillmentStatus: 'Fulfilled',
    shippingStatus: 'Delivered',
    courier: 'Shadowfax',
    awbNumber: 'WIQ-AWB-2026-1004',
    deliveryCity: 'Bengaluru',
    pincode: '560034',
    expectedDeliveryDate: new Date(Date.now() - 3600000 * 24),
    deliveredAt: new Date(Date.now() - 3600000 * 26),
  },
  {
    orderId: 'WIQ-ORD-1005',
    customerName: 'Kunal Verma',
    channel: 'B2B',
    orderDate: new Date(Date.now() - 3600000 * 12),
    fulfillmentCenter: 'WareIQ Delhi NCR Fulfillment Hub',
    items: [
      { sku: 'WIQ-HOM-401', name: 'Ergonomic Memory Foam Lumbar Cushion', quantity: 20, unitPrice: 650 },
    ],
    totalItems: 20,
    totalAmount: 13000,
    paymentStatus: 'Paid',
    fulfillmentStatus: 'Picked',
    shippingStatus: 'Order Confirmed',
    courier: 'Delhivery',
    awbNumber: 'WIQ-AWB-2026-1005',
    deliveryCity: 'Chandigarh',
    pincode: '160017',
    expectedDeliveryDate: new Date(Date.now() + 3600000 * 48),
  },
];
